// Generated by ts-to-zod
import { z } from "zod";

export const renewRequestSchema = z.object({
  refreshToken: z.string(),
  accessToken: z.string(),
});

export const revokeRequestSchema = z.object({
  id: z.string(),
});

export const signInRequestSchema = z.object({
  username: z.string(),
  password: z.string(),
  rememberMe: z.boolean(),
});

export const signUpRequestSchema = z.object({
  username: z.string(),
  email: z.string(),
  phoneNumber: z.string(),
  password: z.string(),
});

export const createSkillRequestSchema = z.object({
  name: z.string(),
});

export const updateSkillRequestSchema = z.object({
  id: z.string(),
  name: z.string(),
});

export const roleRequestSchema = z.object({
  roleId: z.string(),
});

export const skillRequestSchema = z.object({
  skillId: z.string(),
});

export const updateUserRequestSchema = z.object({
  email: z.string().optional(),
  phoneNumber: z.string().optional(),
  password: z.string().optional(),
  isDeleted: z.boolean().optional(),
});

export const recoverPasswordRequestSchema = z.object({
  password: z.string(),
  verificationCode: z.string(),
});

export const createUserRoleRequestSchema = z.object({
  name: z.string(),
});

export const updateUserRoleRequestSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
});

export const createUserRoleClaimsRequestSchema = z.object({
  roleId: z.string(),
  claimType: z.string(),
  claimValue: z.string(),
});

export const updateUserRoleClaimsRequestSchema = z.object({
  claimType: z.string(),
  claimValue: z.string(),
});

export const createUserScheduleRequestSchema = z.object({
  userId: z.string(),
  date: z.string(),
  startAt: z.string(),
  endAt: z.string(),
});

export const updateUserScheduleRequestSchema = z.object({
  date: z.string().optional(),
  startAt: z.string().optional(),
  endAt: z.string().optional(),
});

export const createProjectRequestSchema = z.object({
  workspaceId: z.string(),
  name: z.string(),
});

export const updateProjectRequestSchema = z.object({
  projectId: z.string(),
  name: z.string(),
  isDeleted: z.boolean().optional(),
});

export const restoreProjectRequestSchema = z.object({
  projectId: z.string(),
});

export const addUserRequestSchema = z.object({
  id: z.string(),
  userId: z.string(),
});

export const createProjectRoleRequestSchema = z.object({
  name: z.string(),
  projectId: z.string(),
});

export const updateProjectRoleRequestSchema = z.object({
  id: z.string(),
  name: z.string(),
});

export const createProjectRoleClaimsRequestSchema = z.object({
  value: z.string(),
  roleId: z.string(),
});

export const updateProjectRoleClaimsRequestSchema = z.object({
  id: z.string(),
  value: z.string(),
});

export const createProjectThreadRequestSchema = z.object({
  projectId: z.string(),
  fromId: z.string(),
  title: z.string(),
  text: z.string(),
});

export const updateProjectThreadRequestSchema = z.object({
  id: z.string(),
  fromId: z.string(),
  title: z.string(),
  text: z.string(),
  isDeleted: z.boolean().optional(),
});

export const createProjectThreadCommentRequestSchema = z.object({
  threadId: z.string(),
  fromId: z.string(),
  text: z.string(),
});

export const updateProjectThreadCommentRequestSchema = z.object({
  threadCommentId: z.string(),
  text: z.string(),
  isDeleted: z.boolean().optional(),
});

export const createSectionRequestSchema = z.object({
  projectId: z.string(),
  name: z.string(),
});

export const updateSectionRequestSchema = z.object({
  sectionId: z.string(),
  name: z.string(),
  isDeleted: z.boolean().optional(),
});

export const createTaskRequestSchema = z.object({
  id: z.string(),
  name: z.string(),
  isArchived: z.boolean(),
  startedDate: z.string(),
  endDate: z.string(),
});

export const updateTaskRequestSchema = z.object({
  id: z.string(),
  name: z.string(),
  isArchived: z.boolean(),
  isDeleted: z.boolean().optional(),
  startedDate: z.string().optional(),
  endDate: z.string().optional(),
});

export const addTaskAssigneeRequestSchema = z.object({
  taskId: z.string(),
  userId: z.string(),
});

export const removeTaskAssigneeRequestSchema = z.object({
  taskId: z.string(),
  userId: z.string(),
});

export const createTaskActivityRequestSchema = z.object({
  projectId: z.string(),
  taskId: z.string(),
  activityId: z.string(),
  fromId: z.string(),
  date: z.string(),
  workHours: z.number(),
});

export const updateTaskActivityRequestSchema = z.object({
  taskActivityId: z.string(),
  taskId: z.string(),
  activityId: z.string(),
  fromId: z.string(),
  workHours: z.number(),
});

export const createTaskCommentRequestSchema = z.object({
  taskId: z.string(),
  authorId: z.string(),
  content: z.string(),
});

export const updateTaskCommentRequestSchema = z.object({
  id: z.string(),
  fromId: z.string(),
  content: z.string().optional(),
});

export const createTaskDirectoryRequestSchema = z.object({
  taskId: z.string(),
  name: z.string(),
});

export const updateTaskDirectoryRequestSchema = z.object({
  id: z.string(),
  name: z.string(),
  isDeleted: z.boolean().optional(),
});

export const createTaskEvaluationRequestSchema = z.object({
  taskId: z.string(),
  activityId: z.string(),
  hours: z.number(),
});

export const updateTaskEvaluationRequestSchema = z.object({
  evaluationId: z.string(),
  activityId: z.string(),
  hours: z.number(),
});

export const createTaskTodoListRequestSchema = z.object({
  taskId: z.string(),
});

export const updateTaskTodoListRequestSchema = z.object({
  id: z.string(),
  isDeleted: z.boolean().optional(),
});

export const createTaskTodoListItemRequestSchema = z.object({
  taskTodoListId: z.string(),
  name: z.string(),
  duration: z.number(),
  startedDate: z.string(),
  endDate: z.string().optional(),
});

export const updateTaskTodoListItemRequestSchema = z.object({
  id: z.string(),
  name: z.string(),
  duration: z.number(),
  isCompleted: z.boolean(),
  completedAt: z.string().optional(),
  startedDate: z.string(),
  endDate: z.string().optional(),
});

export const createWorkspaceRequestSchema = z.object({
  name: z.string(),
});

export const updateWorkspaceRequestSchema = z.object({
  name: z.string(),
});

export const createWorkspaceDirectoryRequestSchema = z.object({
  workspaceId: z.string(),
  name: z.string(),
});

export const updateWorkspaceDirectoryRequestSchema = z.object({
  name: z.string(),
});

export const createWorkspacePositionRequestSchema = z.object({
  workspaceId: z.string(),
  name: z.string(),
});

export const updateWorkspacePositionRequestSchema = z.object({
  name: z.string(),
});

export const createWorkspaceRoleRequestSchema = z.object({
  workspaceId: z.string(),
  name: z.string(),
});

export const updateWorkspaceRoleRequestSchema = z.object({
  name: z.string(),
});

export const createWorkspaceRoleClaimRequestSchema = z.object({
  roleId: z.string(),
  value: z.string(),
});

export const updateWorkspaceRoleClaimRequestSchema = z.object({
  value: z.string(),
});

export const updateWorkspaceUserRequestSchema = z.object({
  roleId: z.string(),
  positionId: z.string(),
});

export const uploadFileRequestSchema = z.object({
  fromId: z.string(),
  content: z.array(z.number()),
  fileName: z.string(),
  contentType: z.string(),
});

const notificationTypesSchema = z.any();

export const verifyUserRequestSchema = z.object({
  id: z.string(),
  code: z.string(),
  type: notificationTypesSchema,
});

export const generateVerificationCodeRequestSchema = z.object({
  email: z.string(),
  type: notificationTypesSchema,
});
